### ISSUE TITLE
Hyperparameters of the bottleneck

### ISSUE THREAD

**Issue by cdjhz** [openai/DALL-E#11]
Thanks for releasing the paper as well as the codes! 

Could you give some hints on the hyperparameters of the bottleneck that might affect the performance?

1. The downsampling ratio. In the original VQ-VAE paper, they only use 4 times downsampling (comparing to 8 in DALL-E) and it seems their generated images lack a global structure (I assumed also because they didn't use a powerful prior model). Is that using a higher downsampling rate, the global structure is better preserved? Or easier for the prior model to learn?

2. The codebook size is set to 2^13, have you tried using smaller codebook size? Presumably, as the codebook size shrinks, the VAE can hardly reconstruct the image. What does the reconstructed image with a small codebook look like? Is the texture still preserved but the global structure distorted or something else?

I also have an additional question to the inference stage of the model. Is the image tokens sampled from the prior transformer auto-regressively or using other searching technique? Also, how to control the number of the generated image tokens to be exactly 32 * 32?

**Comment by adityaramesh** [comment]
Sure --

1. The heavy downsampling with the dVAE is simply to reduce memory usage of the transformer. If we used 4x downsampling, we'd get sharper reconstructions and need a smaller vocabulary size, but since the context size of the transformer would become 4x larger, we wouldn't be able to train as large of a model given a fixed amount of compute.

2. Codebook sizes of 256 or 512 still work fine, but the reconstructions are a bit blurrier. Smaller codebook sizes actually make it _easier_ for the transformer to capture the global structure -- i.e., the larger the codebook size, the larger the size of the transformer required to get coherent objects. This is because more of the high-frequency information / fine details are preserved by the larger codebook, and likelihood models tend to capture all of this first before moving on to the other "important" bits.

Yes, during inference, the tokens are sampled autoregressively. The procedure is similar to what you'd do for a vanilla LM with context size 1024. We rerank the samples from the transformer using CLIP (in the blog post, we show the top 32 of 512).

**Comment by hust-nj** [comment]
> Sure --
> 
> 1. The heavy downsampling with the dVAE is simply to reduce memory usage of the transformer. If we used 4x downsampling, we'd get sharper reconstructions and need a smaller vocabulary size, but since the context size of the transformer would become 4x larger, we wouldn't be able to train as large of a model given a fixed amount of compute.
> 2. Codebook sizes of 256 or 512 still work fine, but the reconstructions are a bit blurrier. Smaller codebook sizes actually make it _easier_ for the transformer to capture the global structure -- i.e., the larger the codebook size, the larger the size of the transformer required to get coherent objects. This is because more of the high-frequency information / fine details are preserved by the larger codebook, and likelihood models tend to capture all of this first before moving on to the other "important" bits.
> 
> Yes, during inference, the tokens are sampled autoregressively. The procedure is similar to what you'd do for a vanilla LM with context size 1024. We rerank the samples from the transformer using CLIP (in the blog post, we show the top 32 of 512).

Hi, I wonder that how to generate muliple 32x32 token images(for example, 512 token images), do you use beam search with bin 512?

**Comment by adityaramesh** [comment]
We just use standard autoregressive sampling for the transformer (along with temperature reduction) -- we don't use beam search.

**Comment by hust-nj** [comment]
Thanks for answering! Does beam search can further improve the image generation performance than naively random sampling token in one step?
