### ISSUE TITLE
How to generate vocabulary for the BPE-encoding of text?

### ISSUE THREAD

**Issue by liuqk3** [openai/DALL-E#22]
Hi, @adityaramesh, This is an amazing work!
In the paper, it mentioned that the lowercased text caption is BPE-encoded using at most 256 tokens with vocabulary size 16384. Here are my two questions:
1) How to get the vocabulary? Is it obtained by collecting all subword uints in the captions of training data? 
2) How to decide the vocabulary size 16384? I can not get any other information from the paper about this value.

Thanks

**Comment by adityaramesh** [comment]
Hi Qiankun,

The vocabulary used to create the BPE for DALL-E is obtained by lowercasing the text and splitting on anything except a-z. This includes digits (so we don't merge digits), punctuation (e.g., apostrophes), and spaces (we don't allow spaces to get merged with adjacent words). The vocabulary size was set to 16k mainly because of memory constraints; ideally, I would have liked to use 128k.
