### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DandelionBones** [openai/DALL-E#23]
Hello i am brand new to the github community and coding, i have zero idea how to install this but im an artist and it would be an excellent resource for non copyrighted images, i know its alot to ask but can someone please tell me how to install this code i made my account for this specifically for this

**Comment by ekko95** [comment]
Yeah can someone make a video or something, i have everything i needed installed but  i still cant figure it out

**Comment by 7exe** [comment]
If you're thinking of generating images as given in https://openai.com/blog/dall-e/ then that is not possible as of now, since openAI has not given us access to the larger CLIP model nor the actual text to image transformer that dall-e uses, but you can generate images by using the small CLIP model, check out https://github.com/openai/DALL-E/issues/17#issuecomment-797507142 for examples & info regarding that.

**Comment by fractaldna22** [comment]
customzed notebook. We've actually come a long way and I can pretty much make whatever dalle can make. Im not releasing that notebook because its not mine to share, but i can share this which I tweaked to perfection as far as that VAE is concerned. 

https://colab.research.google.com/drive/1ID_Y2SyKqsfflxaXB5YQdY33Fytvmja2?usp=sharing

check out https://twitter.com/advadnoun for the other notebooks.
